# SPDX-FileCopyrightText: 2025 Jacques Supcik
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build CI workflow
        uses: adafruit/workflows-circuitpython-libs/build@main
